export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const REMOVE_ALL_FROM_CART='REMOVE_ALL_FROM_CART';
export const CLEAR_CART='CLEAR_CART';
export const CART_ITEMS='CART_ITEMS';
export const INC_CART_QUANTITY="INC_CART_QUANTITY"
export const DEC_CART_QUANTITY="DEC_CART_QUANTITY"
export const GET_WISHLIST='GET_WISHLIST';
export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST='REMOVE_FROM_WISHLIST';
export const GET_CATEGORIES='GET_CATEGORIES'



